#!/usr/bin/env bun
/**
 * This script generates an embedded assets module from the frontend build.
 * It reads all files from frontend/dist and creates a TypeScript module
 * with native Bun file imports using `import ... with { type: 'file' }`.
 * 
 * This approach:
 * - Embeds files directly into the compiled binary via Bun's native bundler
 * - Enables lazy loading (files read on demand, not at startup)
 * - Provides zero-copy file serving when combined with Bun.file()
 */

import fs from 'fs';
import path from 'path';

const FRONTEND_DIST = path.join(import.meta.dir, '../../frontend/dist');
const OUTPUT_FILE = path.join(import.meta.dir, '../src/embedded-assets.ts');

const MIME_TYPES: Record<string, string> = {
  '.html': 'text/html',
  '.js': 'application/javascript',
  '.css': 'text/css',
  '.json': 'application/json',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif': 'image/gif',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.ttf': 'font/ttf',
  '.eot': 'application/vnd.ms-fontobject',
};

function getMimeType(filePath: string): string {
  const ext = path.extname(filePath).toLowerCase();
  return MIME_TYPES[ext] || 'application/octet-stream';
}

interface AssetInfo {
  relativePath: string;  // Path relative to frontend/dist
  urlPath: string;       // URL path (e.g., /index.html)
  contentType: string;
}

function collectFiles(dir: string, prefix: string = ''): AssetInfo[] {
  const entries: AssetInfo[] = [];
  
  if (!fs.existsSync(dir)) {
    console.error(`Frontend dist directory not found: ${dir}`);
    console.error('Run "bun run build:frontend" first.');
    process.exit(1);
  }
  
  const items = fs.readdirSync(dir, { withFileTypes: true });
  
  for (const item of items) {
    const fullPath = path.join(dir, item.name);
    const urlPath = prefix ? `${prefix}/${item.name}` : `/${item.name}`;
    const relativePath = path.relative(FRONTEND_DIST, fullPath);
    
    if (item.isDirectory()) {
      entries.push(...collectFiles(fullPath, urlPath));
    } else {
      entries.push({
        relativePath,
        urlPath,
        contentType: getMimeType(item.name),
      });
    }
  }
  
  return entries;
}

function generateModule(assets: AssetInfo[]): string {
  const lines: string[] = [
    '// AUTO-GENERATED FILE - DO NOT EDIT',
    '// @ts-nocheck - Bun file imports are validated by the bundler, not tsc',
    '// Generated by scripts/embed-assets.ts',
    '// Run "bun run embed" to regenerate',
    '//',
    '// Uses Bun native file embedding for zero-copy serving',
    '',
  ];
  
  // Generate imports with native file embedding
  const importLines: string[] = [];
  const mapEntries: string[] = [];
  
  for (let i = 0; i < assets.length; i++) {
    const asset = assets[i];
    const varName = `asset${i}`;
    // Import path relative to src/ directory (where embedded-assets.ts lives)
    const importPath = `../../frontend/dist/${asset.relativePath}`;
    
    importLines.push(`import ${varName} from ${JSON.stringify(importPath)} with { type: "file" };`);
    mapEntries.push(`  ${JSON.stringify(asset.urlPath)}: { path: ${varName}, contentType: ${JSON.stringify(asset.contentType)} },`);
  }
  
  lines.push(...importLines);
  lines.push('');
  lines.push('export interface EmbeddedAsset {');
  lines.push('  path: string;  // Path to embedded file (works with Bun.file())');
  lines.push('  contentType: string;');
  lines.push('}');
  lines.push('');
  lines.push('export const EMBEDDED_ASSETS: Record<string, EmbeddedAsset> = {');
  lines.push(...mapEntries);
  lines.push('};');
  lines.push('');
  
  return lines.join('\n');
}

// Main
console.log('📦 Generating native asset imports...');
const assets = collectFiles(FRONTEND_DIST);
console.log(`   Found ${assets.length} files`);

const moduleContent = generateModule(assets);
fs.writeFileSync(OUTPUT_FILE, moduleContent);

const stats = fs.statSync(OUTPUT_FILE);
console.log(`   Generated ${OUTPUT_FILE}`);
console.log(`   Size: ${(stats.size / 1024).toFixed(1)} KB`);
console.log('✅ Done (using Bun native file embedding)');
